<a href="https://colab.research.google.com/github/Sanjidarema/CSC477-HW1/blob/main/Data_Processing_Lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

# Creation of sample data
data1 = {
    "ID": [1, 2, 3, 4, 4, 5, 6, 6],
    "Name": ["Alice", "Bob", "Charlie", "David", "David", "Eve", "Frank", "Frank"],
    "Age": [25, 30, 35, 40, 40, 28, 50, 50]
}

df1 = pd.DataFrame(data1)

df1

   ID     Name  Age
0   1    Alice   25
1   2      Bob   30
2   3  Charlie   35
3   4    David   40
4   4    David   40
5   5      Eve   28
6   6    Frank   50
7   6    Frank   50

In [2]:
df_no_duplicate = df1.drop_duplicates(keep='first')
df_no_duplicate

   ID     Name  Age
0   1    Alice   25
1   2      Bob   30
2   3  Charlie   35
3   4    David   40
5   5      Eve   28
6   6    Frank   50

In [3]:
import pandas as pd

# Creation of sample data
data2 = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve"],
    "Age": [25, 30, None, 40, 28],
    "Salary": [50000, 60000, 55000, None, 58000]
}

df2 = pd.DataFrame(data2)

df2

      Name   Age   Salary
0    Alice  25.0  50000.0
1      Bob  30.0  60000.0
2  Charlie   NaN  55000.0
3    David  40.0      NaN
4      Eve  28.0  58000.0

In [4]:
# Deleting rows with missing values

df2_no_missing = df2.dropna()
print("Dataset after removing rows with missing values:")
df2_no_missing

Dataset after removing rows with missing values:

    Name   Age   Salary
0  Alice  25.0  50000.0
1    Bob  30.0  60000.0
4    Eve  28.0  58000.0

In [5]:
import pandas as pd

# Creation of sample data
data2 = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve"],
    "Age": [25, 30, None, 40, 28],
    "Salary": [50000, 60000, 55000, None, 58000]
}

df2 = pd.DataFrame(data2)

# Fill missing values with a specific value
df2_filled = df2.fillna(0)

df2_filled

      Name   Age   Salary
0    Alice  25.0  50000.0
1      Bob  30.0  60000.0
2  Charlie   0.0  55000.0
3    David  40.0      0.0
4      Eve  28.0  58000.0

In [6]:
mean_age = df2['Age'].mean()
mean_salary = df2['Salary'].mean()

print("Mean Age:", mean_age)
print("Mean Salary:", mean_salary)

Mean Age: 30.75
Mean Salary: 55750.0

In [7]:
df_mean = df2.copy()

df_mean = df_mean.assign(
    Age=df_mean['Age'].fillna(df_mean['Age'].mean()),
    Salary=df_mean['Salary'].fillna(df_mean['Salary'].mean())
)

df_mean

      Name    Age   Salary
0    Alice  25.00  50000.0
1      Bob  30.00  60000.0
2  Charlie  30.75  55000.0
3    David  40.00  55750.0
4      Eve  28.00  58000.0

In [8]:
# Filling missing values with the mean
import pandas as pd

# Creation of sample data
data2 = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve"],
    "Age": [25, 30, None, 40, 28],
    "Salary": [50000, 60000, 55000, None, 58000]
}

df2 = pd.DataFrame(data2)

df2

df_mean = df2.copy()

df_mean = df_mean.assign(
    Age=df_mean["Age"].fillna(df_mean["Age"].mean()),
    Salary=df_mean["Salary"].fillna(df_mean["Salary"].mean())
)

df_mean

      Name    Age   Salary
0    Alice  25.00  50000.0
1      Bob  30.00  60000.0
2  Charlie  30.75  55000.0
3    David  40.00  55750.0
4      Eve  28.00  58000.0

In [11]:
import pandas as pd

# Creating a dataset with missing values
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Age': [25, 30, None, 40, 28],          # Missing Age for Charlie
    'Salary': [50000, 60000, 55000, None, 58000],  # Missing Salary for David
    'City': ['New York', 'Los Angeles', None, 'Chicago', 'Houston']  # Missing City for Charlie
}

df = pd.DataFrame(data)

print("Original Dataset:\n")
df

Original Dataset:

      Name   Age   Salary         City
0    Alice  25.0  50000.0     New York
1      Bob  30.0  60000.0  Los Angeles
2  Charlie   NaN  55000.0         None
3    David  40.0      NaN      Chicago
4      Eve  28.0  58000.0      Houston

In [12]:
# Creating a copy of the dataset for Median Imputation
df_median = df.copy()

# Applying Median Imputation
df_median['Age'] = df_median['Age'].fillna(df_median['Age'].median())
df_median['Salary'] = df_median['Salary'].fillna(df_median['Salary'].median())

# Applying Mode Imputation for Categorical Column (City)
df_median['City'] = df_median['City'].fillna(df_median['City'].mode()[0])

print("\nDataset after Median and Mode Imputation:\n")
df_median

Dataset after Median and Mode Imputation:

      Name   Age   Salary         City
0    Alice  25.0  50000.0     New York
1      Bob  30.0  60000.0  Los Angeles
2  Charlie  29.0  55000.0      Chicago
3    David  40.0  56500.0      Chicago
4      Eve  28.0  58000.0      Houston

In [13]:
from sklearn.preprocessing import StandardScaler
import pandas as pd

# Sample data
data = {
    "Feature1": [10, 20, 30, 40, 50],
    "Feature2": [100, 200, 300, 400, 500]
}

df = pd.DataFrame(data)

# --- Standardization (Z-score Scaling) ---
scaler_standard = StandardScaler()

standardized_data = scaler_standard.fit_transform(df)

# Convert standardized data to DataFrame for better visualization
df_standardized = pd.DataFrame(
    standardized_data,
    columns=["Feature1", "Feature2"]
)

# Display standardized data
print("\nStandardized Data (Z-score Scaling):")
df_standardized

Standardized Data (Z-score Scaling):

   Feature1  Feature2
0 -1.414214 -1.414214
1 -0.707107 -0.707107
2  0.000000  0.000000
3  0.707107  0.707107
4  1.414214  1.414214

In [14]:
# Sample data
data = ['Red', 'Green', 'Blue', 'Red', 'Green']

# Create DataFrame
df = pd.DataFrame(data, columns=['Color'])

# Apply One-Hot Encoding
one_hot_encoded = pd.get_dummies(df['Color'], dtype=int)

# Display the One-Hot Encoded Data
print("One-Hot Encoded Data:")
print(one_hot_encoded)

One-Hot Encoded Data:
   Blue  Green  Red
0     0      0    1
1     0      1    0
2     1      0    0
3     0      0    1
4     0      1    0